kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deploy-default
  namespace: default
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - secrets
  - services
  - persistentvolumeclaims
  verbs:
  - get
  - list
  - watch
  - patch
  - create
- apiGroups:
  - extensions
  - apps
  resources:
  - deployments
  - replicasets
  verbs:
  - get
  - list
  - watch
  - patch
  - create 
