# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: deploy-ubernetes-pod
subjects:
- kind: User
  name: default # Name is case sensitive
  namespace: ubernetes
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: service-default
  apiGroup: rbac.authorization.k8s.io
