#-> Include latest nginx image from default library
FROM nginx:latest
#-> Copy index file to document root
COPY index.html /usr/share/nginx/html/index.html
#-> Export private container port 80
EXPOSE 80
