node {

    checkout scm

    env.DOCKER_API_VERSION="1.23"

    sh "git rev-parse --short HEAD > commit-id"

    tag = readFile('commit-id').replace("\n", "").replace("\r", "")
    appName = "hello-world"
    registryHost = "127.0.0.1:30400/"
    imageName = "${registryHost}${appName}:${tag}"
    env.BUILDIMG=imageName

    stage "Build"

        sh "docker build -t ${imageName} -f applications/hello-world/Dockerfile applications/hello-world"

    stage "Push"

        sh "docker push ${imageName}"

    stage "Smoke Test"

        sh "echo 'some bullshit here'"
        input "Deploy to production?"

    stage "Deploy"

        sh "sed 's#127.0.0.1:30400/hello-world:latest#'$BUILDIMG'#' applications/hello-world/k8s/deployment.yaml | kubectl apply -f -"
        sh "kubectl rollout status deployment/hello-world"

}
